// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v3.1.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// C:\Users\admin\Desktop\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_codegen.cpp:454

#ifndef _TAO_IDL_DEMOS_NUFA5B_H_
#define _TAO_IDL_DEMOS_NUFA5B_H_

#include /**/ "ace/pre.h"

#include "DemoC.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/UB_String_SArguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

// TAO_IDL - Generated from
// C:\Users\admin\Desktop\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // C:\Users\admin\Desktop\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:931

  

  template<>
  class SArg_Traits< ::DemoIdlModule::DemoTopic1>
    : public
        Var_Size_SArg_Traits_T<
            ::DemoIdlModule::DemoTopic1,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// C:\Users\admin\Desktop\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_module\module_sh.cpp:34

namespace POA_DemoIdlModule
{
  


// TAO_IDL - Generated from
// C:\Users\admin\Desktop\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_module\module_sh.cpp:65

} // module DemoIdlModule

#include /**/ "ace/post.h"

#endif /* ifndef */

