// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v3.1.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// C:\Users\admin\Desktop\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_codegen.cpp:372


#include "DemoTypeSupportC.h"
#include "tao/CDR.h"
#include "cstring"

#if !defined (__ACE_INLINE__)
#include "DemoTypeSupportC.inl"
#endif /* !defined INLINE */
// TAO_IDL - Generated from
// C:\Users\admin\Desktop\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for DemoIdlModule::DemoTopic1TypeSupport.

DemoIdlModule::DemoTopic1TypeSupport_ptr
TAO::Objref_Traits<DemoIdlModule::DemoTopic1TypeSupport>::duplicate (DemoIdlModule::DemoTopic1TypeSupport_ptr p)
{
  return DemoIdlModule::DemoTopic1TypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<DemoIdlModule::DemoTopic1TypeSupport>::release (DemoIdlModule::DemoTopic1TypeSupport_ptr p)
{
  ::CORBA::release (p);
}

DemoIdlModule::DemoTopic1TypeSupport_ptr
TAO::Objref_Traits<DemoIdlModule::DemoTopic1TypeSupport>::nil ()
{
  return DemoIdlModule::DemoTopic1TypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DemoIdlModule::DemoTopic1TypeSupport>::marshal (const DemoIdlModule::DemoTopic1TypeSupport_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



DemoIdlModule::DemoTopic1TypeSupport::DemoTopic1TypeSupport ()
{}DemoIdlModule::DemoTopic1TypeSupport_ptr
DemoIdlModule::DemoTopic1TypeSupport::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return DemoTopic1TypeSupport::_duplicate (
      dynamic_cast<DemoTopic1TypeSupport_ptr> (_tao_objref));
}

DemoIdlModule::DemoTopic1TypeSupport_ptr
DemoIdlModule::DemoTopic1TypeSupport::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return DemoTopic1TypeSupport::_duplicate (
      dynamic_cast<DemoTopic1TypeSupport_ptr> (_tao_objref));
}

DemoIdlModule::DemoTopic1TypeSupport_ptr
DemoIdlModule::DemoTopic1TypeSupport::_nil ()
{
  return nullptr;
}

DemoIdlModule::DemoTopic1TypeSupport_ptr
DemoIdlModule::DemoTopic1TypeSupport::_duplicate (DemoTopic1TypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DemoIdlModule::DemoTopic1TypeSupport::_tao_release (DemoTopic1TypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DemoIdlModule::DemoTopic1TypeSupport::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:DemoIdlModule/DemoTopic1TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DemoIdlModule::DemoTopic1TypeSupport::_interface_repository_id () const
{
  return "IDL:DemoIdlModule/DemoTopic1TypeSupport:1.0";
}

::CORBA::Boolean
DemoIdlModule::DemoTopic1TypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\admin\Desktop\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for DemoIdlModule::DemoTopic1DataWriter.

DemoIdlModule::DemoTopic1DataWriter_ptr
TAO::Objref_Traits<DemoIdlModule::DemoTopic1DataWriter>::duplicate (DemoIdlModule::DemoTopic1DataWriter_ptr p)
{
  return DemoIdlModule::DemoTopic1DataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<DemoIdlModule::DemoTopic1DataWriter>::release (DemoIdlModule::DemoTopic1DataWriter_ptr p)
{
  ::CORBA::release (p);
}

DemoIdlModule::DemoTopic1DataWriter_ptr
TAO::Objref_Traits<DemoIdlModule::DemoTopic1DataWriter>::nil ()
{
  return DemoIdlModule::DemoTopic1DataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DemoIdlModule::DemoTopic1DataWriter>::marshal (const DemoIdlModule::DemoTopic1DataWriter_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



DemoIdlModule::DemoTopic1DataWriter::DemoTopic1DataWriter ()
{}DemoIdlModule::DemoTopic1DataWriter_ptr
DemoIdlModule::DemoTopic1DataWriter::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return DemoTopic1DataWriter::_duplicate (
      dynamic_cast<DemoTopic1DataWriter_ptr> (_tao_objref));
}

DemoIdlModule::DemoTopic1DataWriter_ptr
DemoIdlModule::DemoTopic1DataWriter::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return DemoTopic1DataWriter::_duplicate (
      dynamic_cast<DemoTopic1DataWriter_ptr> (_tao_objref));
}

DemoIdlModule::DemoTopic1DataWriter_ptr
DemoIdlModule::DemoTopic1DataWriter::_nil ()
{
  return nullptr;
}

DemoIdlModule::DemoTopic1DataWriter_ptr
DemoIdlModule::DemoTopic1DataWriter::_duplicate (DemoTopic1DataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DemoIdlModule::DemoTopic1DataWriter::_tao_release (DemoTopic1DataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DemoIdlModule::DemoTopic1DataWriter::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:DemoIdlModule/DemoTopic1DataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DemoIdlModule::DemoTopic1DataWriter::_interface_repository_id () const
{
  return "IDL:DemoIdlModule/DemoTopic1DataWriter:1.0";
}

::CORBA::Boolean
DemoIdlModule::DemoTopic1DataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\admin\Desktop\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for DemoIdlModule::DemoTopic1DataReader.

DemoIdlModule::DemoTopic1DataReader_ptr
TAO::Objref_Traits<DemoIdlModule::DemoTopic1DataReader>::duplicate (DemoIdlModule::DemoTopic1DataReader_ptr p)
{
  return DemoIdlModule::DemoTopic1DataReader::_duplicate (p);
}

void
TAO::Objref_Traits<DemoIdlModule::DemoTopic1DataReader>::release (DemoIdlModule::DemoTopic1DataReader_ptr p)
{
  ::CORBA::release (p);
}

DemoIdlModule::DemoTopic1DataReader_ptr
TAO::Objref_Traits<DemoIdlModule::DemoTopic1DataReader>::nil ()
{
  return DemoIdlModule::DemoTopic1DataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DemoIdlModule::DemoTopic1DataReader>::marshal (const DemoIdlModule::DemoTopic1DataReader_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



DemoIdlModule::DemoTopic1DataReader::DemoTopic1DataReader ()
{}DemoIdlModule::DemoTopic1DataReader_ptr
DemoIdlModule::DemoTopic1DataReader::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return DemoTopic1DataReader::_duplicate (
      dynamic_cast<DemoTopic1DataReader_ptr> (_tao_objref));
}

DemoIdlModule::DemoTopic1DataReader_ptr
DemoIdlModule::DemoTopic1DataReader::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return DemoTopic1DataReader::_duplicate (
      dynamic_cast<DemoTopic1DataReader_ptr> (_tao_objref));
}

DemoIdlModule::DemoTopic1DataReader_ptr
DemoIdlModule::DemoTopic1DataReader::_nil ()
{
  return nullptr;
}

DemoIdlModule::DemoTopic1DataReader_ptr
DemoIdlModule::DemoTopic1DataReader::_duplicate (DemoTopic1DataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DemoIdlModule::DemoTopic1DataReader::_tao_release (DemoTopic1DataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DemoIdlModule::DemoTopic1DataReader::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/DataReaderEx:1.0") == 0 ||
      std::strcmp (value, "IDL:DemoIdlModule/DemoTopic1DataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DemoIdlModule::DemoTopic1DataReader::_interface_repository_id () const
{
  return "IDL:DemoIdlModule/DemoTopic1DataReader:1.0";
}

::CORBA::Boolean
DemoIdlModule::DemoTopic1DataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

